 services:
  - type: web
    name: TAXI-EXPRESS
    env: php
    plan: free

    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate --ansi
      php artisan migrate:fresh --force
      php artisan config:clear
      php artisan route:clear
      php artisan view:clear
    
    startCommand: heroku-php-apache2 public/

    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://taxi-express-zm4i.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d3sn59ruibrs73aefc0g-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: taxi_express_00zt
      - key: DB_USERNAME
        value: taxiexpress
      - key: DB_PASSWORD
        value: ph0ASAdfiiGq9kavGxkdV1GiaS6lC77e
      - key: SESSION_DRIVER
        value: database
      - key: LOG_CHANNEL
        value: stack